# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PH-tree
locale: "en-US"
subtitle: "Subtitle: Version 2.0"
name: "Tilmann Zäschke"

description: >- # this means to ignore newlines until "baseurl:"
  This is the main project site for my PH-tree project.


url: "https://tzaeschke.github.io"
baseurl: "/phtree-site"

repository: "tzaeschke/phtree-site"



email: zoodb (AT) gmx.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tzaeschke
twitter_username: ZooDBMS

keywords: "tilmann, zaeschke, zaschke, PH-tree, phtree, spatial, index, multidimensional, multi-dimensional, index-library"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#remote_theme: "mmistakes/minimal-mistakes@4.9.0"
#theme: minima
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ZooDBMSs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tzaeschke"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/mmistakes"
