#theme: minima
theme: jekyll-theme-cayman

title: PH-Tree's homepage
#description: Bookmark this to keep an eye on my project updates!

email: zoodb(at)gmx.de

twitter_username: ZooDBMS
github_username:  tzaeschke

keywords: "tilmann, zaeschke, zaschke, PH-tree, phtree, spatial, index, multidimensional, multi-dimensional"

highlighter: rouge

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - screenshot.png
  - docs/
